### ISSUE TITLE
2 Errors Running Scripts

### ISSUE THREAD

**Issue by rob26r** [google-coral/project-teachable-sorter#8]
I'm really new to Raspberry Pi but why does every tutorial not properly run??  Must be me...

So I just loaded the operating system (Raspian Buster with Desktop and recommended Software from this site https://www.raspberrypi.org/downloads/raspbian/) on my SD card and inserted into my Pi.

I then followed the directions from here (https://www.coral.ai/projects/teachable-sorter/).

1) Set up the USB Accelerator - no issues.

2) Install libraries - I'm getting this error message, it still loads but getting this error.

```
Collecting edgetpu==2.11.1 (from -r requirements.txt (line 24))
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/edgetpu/
```

**Why am I getting this error message?**

3) python3 sorter.py --opencv 

```
Traceback (most recent call last):
  File "sorter.py", line 23, in <module>
    from scipy import ndimage
ModuleNotFoundError: No module named 'scipy'
```
**Do I just have to install scipy?  Why doesn't it tell me to do that??**

Appreciate any help you can provide?

Thanks.

**Comment by matallan** [comment]
`Traceback (most recent call last):
  File "sorter.py", line 23, in <module>
    from scipy import ndimage
ModuleNotFoundError: No module named 'scipy'`

This throws because scipy is not included in the python environment setup (in the requirements.txt file).

You will need to install scipy. I would recommend installing from:

https://www.piwheels.org/project/scipy/

This manages the installation of scipy with a Raspberry Pi.

**Comment by matallan** [comment]
`Collecting edgetpu==2.11.1 (from -r requirements.txt (line 24))
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/edgetpu/`

This error occurs because you can not access the link any more. If you follow the steps to set up the Coral accelerator from: https://coral.ai/docs/accelerator/get-started/
You will install the requirements to use the coral accelerator.

**Comment by manoj7410** [comment]
Feel free to reopen if the issue still persists.
